### PR TITLE
CPU Input Boost (fixed error while compiling)

### PR DESCRIPTION
**Pull request by EyeCantCU**
This boosts the CPU on touchscreen and touchpad input. Boost frequencies, durations, and number of CPUs to boost are calculated automatically using fudge factors. The only configuration required for functionality is to enable boosting via the /sys/module/cpu_input_boost/parameters/enabled sysfs node.

Edit: fixed cpufreq as a whole while I was at it. It won't happen again... however on  the bright side, Interactive was improved a lot... I'll test everything from now on

### CODE REVIEW

**Comment by scafroglia93** [comment]
These commits are tested ? Your pull request concerning smartmax breaks kernel compilation

**Comment by RJDTWO** [comment]
I will look into that real quick. Should be an easy fix. Typically yes, however I have a much slower system then I used to have.

I apologize for that

**Comment by EyeCantCU** [comment]
@scafroglia93 I fixed this by moving the mentioned function to cpufreq.c. I'll push the changes in a bit. Again I am sincerely sorry about that. I also had to resync Interactive as well too due to moving the function.

Won't happen again. Again, sorry.

**Comment by EyeCantCU** [comment]
Everything is now fixed and this can now be merged.

**Comment by scafroglia93** [comment]
Now we wait the response from PA Team

**Comment by xboxfanj** [comment]
Why do we need this?  I disabled the CAF boost driver and battery life seems to be better without this sort of boosting.  What improvements have you found from adding this to this kernel?

**Comment by EyeCantCU** [comment]
@xboxfanj Oh. Okay. I figured we had still been using as it's defined by the Makefile. The benefit of having this however is to act as a standalone driver for boosting the processor rather than relying on the governor itself to do so. If you don't think its useful, I'll go ahead and close it. I think its better we go this route as its currently the most intelligent boosting driver I know of and the governors themselves don't offer very much in this sense. 

I'd suspect better battery life with this solution for governors that use boosting by default, but governors that don't may take a hit in this aspect. 

Completely up to you though.

**Comment by xboxfanj** [comment]
@RJDTWO did you test it with and without?

**Comment by xboxfanj** [comment]
At this time, this will not be merged.  We do not notice any improvements with it.

**Comment by scafroglia93** [comment]
For this moment push into kernel source the fix for smartmax governor

**Comment by xboxfanj** [comment]
I just removed smartmax and voltage control altogether for now.

**Comment by scafroglia93** [comment]
Thanks!

**Pull request closed without merging**
